# Generated by Django 3.2.15 on 2022-10-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m22', '0002_maintenancestatus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='part',
        ),
    ]
